/**
 * File Templates for Project Initialization
 */

import { stringify as stringifyYaml } from 'yaml';

/**
 * Generate .sysconst/config.yaml content
 */
export function generateProjectConfig(
  projectName: string,
  specFileName: string,
  provider: string = 'openrouter',
  model: string = 'anthropic/claude-3.5-sonnet'
): string {
  return `# System Constitution Project Configuration
# Generated by: sysconst init

project:
  name: ${projectName}
  specFile: ${specFileName}

llm:
  provider: ${provider}
  model: ${model}
  temperature: 0.3
  maxRetries: 3

versioning:
  autoCommit: true
  autoTag: true
  tagPrefix: v
`;
}

/**
 * Generate .gitignore content
 */
export function generateGitignore(): string {
  return `# System Constitution
.sysconst/cache/

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db
Desktop.ini

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Dependencies (if using npm/yarn in project)
node_modules/

# Build output
dist/
build/
`;
}

/**
 * Generate README.md content
 */
export function generateReadme(
  projectName: string,
  specFileName: string,
  description?: string
): string {
  return `# ${projectName}

System Constitution-managed project.

${description ? `## Description\n\n${description}\n\n` : ''}## Specification

- **Spec file**: \`${specFileName}\`
- **Current version**: 1.0.0

## Commands

\`\`\`bash
# Validate specification
sysconst validate ${specFileName}

# Evolve specification with LLM
sysconst evolve ${specFileName} -c "Add new feature"

# View version history
sysconst history

# Bump version manually
sysconst version bump minor -m "Description of changes"

# Check version consistency
sysconst version check
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── .sysconst/           # System Constitution configuration
│   └── config.yaml     # Project settings
├── ${specFileName}     # Main specification
├── .gitignore          # Git ignore rules
└── README.md           # This file
\`\`\`

## Getting Started

1. Edit \`${specFileName}\` to define your system
2. Run \`sysconst validate ${specFileName}\` to check for errors
3. Use \`sysconst evolve\` to make changes with AI assistance
4. Commit changes with \`sysconst version bump\`

## Generated by

System Constitution CLI v1.0.0
`;
}

/**
 * Generate minimal spec template
 */
export function generateMinimalSpecTemplate(projectName: string): string {
  const projectId = projectName.toLowerCase().replace(/[^a-z0-9]/g, '.');
  
  const spec = {
    spec: 'sysconst/v1',
    project: {
      id: projectId,
      name: projectName,
      versioning: {
        strategy: 'semver',
        current: '1.0.0',
      },
    },
    structure: {
      root: 'NodeRef(system.root)',
    },
    domain: {
      nodes: [
        {
          kind: 'System',
          id: 'system.root',
          meta: {
            title: projectName,
            description: 'Main system',
          },
          spec: {
            goals: ['Define your system goals here'],
          },
          children: ['NodeRef(mod.core)'],
        },
        {
          kind: 'Module',
          id: 'mod.core',
          meta: {
            title: 'Core',
          },
          spec: {},
          children: ['NodeRef(entity.example)'],
        },
        {
          kind: 'Entity',
          id: 'entity.example',
          meta: {
            title: 'Example Entity',
          },
          spec: {
            fields: {
              id: { type: 'uuid', required: true },
              name: { type: 'string', required: true },
              createdAt: { type: 'datetime', required: true },
            },
          },
          contracts: [
            { invariant: "name != ''", level: 'hard' },
          ],
        },
      ],
    },
    history: [
      {
        version: '1.0.0',
        basedOn: null,
        changes: [],
        migrations: [],
        notes: 'Initial version',
      },
    ],
  };
  
  return stringifyYaml(spec, { lineWidth: 0 });
}
